### ISSUE TITLE
Project Proposal needed

### ISSUE THREAD

**Issue by docligot** [Mr-Miaral/Mark_Project_Repository#1]
Hi Mark, 

Let's boot up this project!

Given your chosen dataset (Income Classification) https://archive.ics.uci.edu/dataset/2/adult

Let's come up with some possible project directions: 

- Objective/Problem statement
- Current uses/status of the data 
- Related studies that use this data
- User/author expectations

Let's edit this into the readme.md file of the repository. 

Note: for all changes, let's observe the following: 

- Create a branch on Github for Windows and name it based on issue/task being addressed (e.g. creating project proposal)
- Do the edits on your local machine (e.g. editing readme.md)
- Once done, commit the edits, then push to the branch
- Create a pull request to merge the branch into main
- Pull request will require approval, which I will do based on evaluation of the task
- Once approved, changes are brought to main

If you have any questions/clarifications - you can always chat here on issues.

**Comment by Mr-Miaral** [comment]
Hi doc ! I am letting you know that I have added the changes to my readme.md file. Let me know if there should be any changes. Thanks !

**Comment by docligot** [comment]
Ok good. Some next steps: 

- instead of pushing to 'main' create a branch first (as advised above), then make the edits, then push it to the branch, then do a pull request so I can see the edit for approval
- rename the readme.md.txt into readme.md only 
- do the pull request and I'll check it for changes

**Comment by docligot** [comment]
If you need guidance on branching, you can do this on github for windows - under branch, click "new branch" and name it based on the task. (e.g. creating-readme)

**Comment by docligot** [comment]
Closing this issue. We can amend the readme further as we explore the dataset.
